# Exception handling
```
This program executes the following task.
```

# Task
```
Wrap the code in the 'try...catch' construct: console.log(a), let a = 3. And display an error - 'let' must be declared before use'. When executing 1/0, display an error 'can't divide by zero'.
```
